name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:

- type: textarea
  id: feature-description
  attributes:
    label: Description
    description: Fournissez une description claire et concise de la fonctionnalité.
  validations:
    required: true

- type: textarea
  id: implementation-example
  attributes:
    label: Exemple de mise en œuvre
    description: Décrivez comment vous imaginez cette fonctionnalité être mise en œuvre.
  validations:
    required: false

- type: checkboxes
  id: roles-affected
  attributes:
    label: Rôle(s) RP concerné(s)
    description: Sélectionnez quels rôles sur le panel de SOZ seront impactés ou concernés par cette fonctionnalité.
    options:
      - label: Head Security
      - label: Administrateur
      - label: Chef d'équipe
      - label: Formateur
      - label: RH
      - label: Sénior
      - label: Confirmé
      - label: Junior
      - label: En Formation
  validations:
    required: true
    
- type: textarea
  id: interaction-with-features
  attributes:
    label: Interaction avec d'autres fonctionnalités 
    description: Indiquez comment cette fonctionnalité interagira avec les autres fonctionnalités existantes ou à venir.
  validations:
    required: false

- type: textarea
  id: additional-details
  attributes:
    label: Détails supplémentaires
    description: Inclure ici tous les autres détails ou commentaires pertinents.
  validations:
    required: false
